app:
    resource: "@AppBundle/Controller/"
    type:     annotation



users_list:
    path:      /users/list
    defaults:  { _controller: "AppBundle:User:list" }


member_list:
    path:      /member/list
    defaults:  { _controller: "AppBundle:Member:list" }


invest_plan:
    path:      /investplan/create
    defaults:  { _controller: "AppBundle:InvestPlan:create" }


create_unexisting_wallet:
    path:      /wallet/createunexisting
    defaults:  { _controller: "AppBundle:Wallet:createUnexisting" }
