app:
    resource: "@AppBundle/Controller/"
    type:     annotation



users_list:
    path:      /users/list
    defaults:  { _controller: "AppBundle:User:list" }


member_list:
    path:      /member/list
    defaults:  { _controller: "AppBundle:Member:list" }