<?php
/**
 * TL_ROOT/system/modules/autoregistration/languages/ja/tl_page.php 
 * 
 * Contao extension: autoregistration 1.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2009-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['auto_activate_registration']['0'] = "自動アクティベーション";
$GLOBALS['TL_LANG']['tl_page']['auto_activate_registration']['1'] = "自動的に新しいメンバーを(電子メールの確認なしに)有効にします。";
$GLOBALS['TL_LANG']['tl_page']['auto_login_registration']['0'] = "自動ログイン";
$GLOBALS['TL_LANG']['tl_page']['auto_login_registration']['1'] = "自動的に新しいメンバーをログインします。(自動アクティベーションが有効な場合だけ動作します。)";
$GLOBALS['TL_LANG']['tl_page']['auto_login_activation']['0'] = "アクティベーションで自動ログイン";
$GLOBALS['TL_LANG']['tl_page']['auto_login_activation']['1'] = "自動的に新しいメンバーをアクティベーションの確認をしたときにログインします。";
$GLOBALS['TL_LANG']['tl_page']['registration_legend'] = "メンバーの登録";
 
?>
