<?php

namespace AppBundle\Repository;
use AppBundle\Entity\WalletProvider;


/**
 * MemberWalletsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberWalletsRepository extends \Doctrine\ORM\EntityRepository
{


}
