<?php

/**
 * cfg_slider_revolution extension for Contao Open Source CMS
 *
 * Copyright (C) 2011-2015 Codefog
 *
 * @package cfg_slider_revolution
 * @author  Codefog <http://codefog.pl>
 * @author  Kamil Kuzminski <kamil.kuzminski@codefog.pl>
 * @license Commercial
 */

$settings = [];

/**
 * Layer transitions
 */
$settings['layer_transitions'] = [
    'basics'              => ['notransition', 'fade'],
    'slide-simple'        => ['slideup', 'slidedown', 'slideright', 'slideleft', 'slidehorizontal', 'slidevertical'],
    'slide-over'          => ['slideoverup', 'slideoverdown', 'slideoverright', 'slideoverleft', 'slideoverhorizontal', 'slideoververtical'],
    'slide-remove'        => ['slideremoveup', 'slideremovedown', 'slideremoveright', 'slideremoveleft', 'slideremovehorizontal', 'slideremovevertical'],
    'slots-and-boxes'     => ['boxslide', 'slotslide-horizontal', 'slotslide-vertical', 'boxfade', 'slotfade-horizontal', 'slotfade-vertical'],
    'fade-slide'          => ['fadefromright', 'fadefromleft', 'fadefromtop', 'fadefrombottom', 'fadetoleftfadefromright', 'fadetorightfadefromleft', 'fadetotopfadefrombottom', 'fadetobottomfadefromtop'],
    'parallax'            => ['parallaxtoright', 'parallaxtoleft', 'parallaxtotop', 'parallaxtobottom', 'parallaxhorizontal', 'parallaxvertical'],
    'zoom-transitions'    => ['scaledownfromright', 'scaledownfromleft', 'scaledownfromtop', 'scaledownfrombottom', 'zoomout', 'zoomin', 'slotzoom-horizontal', 'slotzoom-vertical'],
    'curtain-transitions' => ['curtain-1', 'curtain-2', 'curtain-3'],
    'premium-transitions' => ['3dcurtain-horizontal', '3dcurtain-vertical', 'cube', 'cube-horizontal', 'incube', 'incube-horizontal', 'turnoff', 'turnoff-vertical', 'papercut', 'flyin'],
    'random'              => ['random-selected', 'random-static', 'random-premium', 'random'],
];

/**
 * Caption styles
 */
$settings['caption_styles'] = [
    'medium_grey',
    'small_text',
    'medium_text',
    'large_text',
    'very_large_text',
    'very_big_white',
    'very_big_black',
    'modern_medium_fat',
    'modern_medium_fat_white',
    'modern_medium_light',
    'modern_big_bluebg',
    'modern_big_redbg',
    'modern_small_text_dark',
    'boxshadow',
    'black',
    'noshadow',
    'thinheadline_dark',
    'thintext_dark',
    'largeblackbg',
    'largepinkbg',
    'largewhitebg',
    'largegreenbg',
    'excerpt',
    'large_bold_grey',
    'medium_thin_grey',
    'small_thin_grey',
    'lightgrey_divider',
    'large_bold_darkblue',
    'medium_bg_darkblue',
    'medium_bold_red',
    'medium_light_red',
    'medium_bg_red',
    'medium_bold_orange',
    'medium_bg_orange',
    'grassfloor',
    'large_bold_white',
    'medium_light_white',
    'mediumlarge_light_white',
    'mediumlarge_light_white_center',
    'medium_bg_asbestos',
    'medium_light_black',
    'large_bold_black',
    'mediumlarge_light_darkblue',
    'small_light_white',
    'roundedimage',
    'large_bg_black',
    'mediumwhitebg',
    'MarkerDisplay',
    'Restaurant-Display',
    'Restaurant-Cursive',
    'Restaurant-ScrollDownText',
    'Restaurant-Description',
    'Restaurant-Price',
    'Restaurant-Menuitem',
    'Furniture-LogoText',
    'Furniture-Plus',
    'Furniture-Title',
    'Furniture-Subtitle',
    'Gym-Display',
    'Gym-Subline',
    'Gym-SmallText',
    'Fashion-SmallText',
    'Fashion-BigDisplay',
    'Fashion-TextBlock',
    'Sports-Display',
    'Sports-DisplayFat',
    'Sports-Subline',
    'Instagram-Caption',
    'News-Title',
    'News-Subtitle',
    'Photography-Display',
    'Photography-Subline',
    'Photography-ImageHover',
    'Photography-Menuitem',
    'Photography-Textblock',
    'Photography-Subline-2',
    'Photography-ImageHover2',
    'WebProduct-Title',
    'WebProduct-SubTitle',
    'WebProduct-Content',
    'WebProduct-Menuitem',
    'WebProduct-Title-Light',
    'WebProduct-SubTitle-Light',
    'WebProduct-Content-Light',
    'FatRounded',
    'NotGeneric-Title',
    'NotGeneric-SubTitle',
    'NotGeneric-CallToAction',
    'NotGeneric-Icon',
    'NotGeneric-Menuitem',
    'MarkerStyle',
    'Gym-Menuitem',
    'Newspaper-Button',
    'Newspaper-Subtitle',
    'Newspaper-Title',
    'Newspaper-Title-Centered',
    'Hero-Button',
    'Video-Title',
    'Video-SubTitle',
    'NotGeneric-Button',
    'NotGeneric-BigButton',
    'WebProduct-Button',
    'Restaurant-Button',
    'Gym-Button',
    'Gym-Button-Light',
    'Sports-Button-Light',
    'Sports-Button-Red',
    'Photography-Button',
    'Newspaper-Button-2'
];

/**
 * Easings
 */
$settings['easings'] = [
    'Default',
    'Linear.easeNone',
    'Power0.easeIn', 'Power0.easeInOut', 'Power0.easeOut',
    'Power1.easeIn', 'Power1.easeInOut', 'Power1.easeOut',
    'Power2.easeIn', 'Power2.easeInOut', 'Power2.easeOut',
    'Power3.easeIn', 'Power3.easeInOut', 'Power3.easeOut',
    'Power4.easeIn', 'Power4.easeInOut', 'Power4.easeOut',
    'Quad.easeIn', 'Quad.easeInOut', 'Quad.easeOut',
    'Cubic.easeIn', 'Cubic.easeInOut', 'Cubic.easeOut',
    'Quart.easeIn', 'Quart.easeInOut', 'Quart.easeOut',
    'Quint.easeIn', 'Quint.easeInOut', 'Quint.easeOut',
    'Strong.easeIn', 'Strong.easeInOut', 'Strong.easeOut',
    'Back.easeIn', 'Back.easeInOut', 'Back.easeOut',
    'Bounce.easeIn', 'Bounce.easeInOut', 'Bounce.easeOut',
    'Circ.easeIn', 'Circ.easeInOut', 'Circ.easeOut',
    'Elastic.easeIn', 'Elastic.easeInOut', 'Elastic.easeOut',
    'Expo.easeIn', 'Expo.easeInOut', 'Expo.easeOut',
    'Sine.easeIn', 'Sine.easeInOut', 'Sine.easeOut',
    'SlowMo.ease',
];

/**
 * Predefined in animations
 */
$settings['animations_in'] = array(
    'LettersFlyInFromBottom' =>
        array(
            'label'  => 'LettersFlyInFromBottom',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => '[100%]',
                    'z'          => '0',
                    'rX'         => 'inherit',
                    'rY'         => 'inherit',
                    'rZ'         => '-35deg',
                    'sX'         => '1',
                    'sY'         => '1',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => 'inherit',
                    'mX'         => '0px',
                    'mY'         => '0px',
                    'e'          => 'Power4.easeInOut',
                    'split'      => 'chars',
                    'splitDelay' => '5',
                ),
        ),
    'LettersFlyInFromLeft'   =>
        array(
            'label'  => 'LettersFlyInFromLeft',
            'config' =>
                array(
                    'x'          => '[-105%]',
                    'y'          => 'inherit',
                    'z'          => '0',
                    'rX'         => '0deg',
                    'rY'         => '0deg',
                    'rZ'         => '-90deg',
                    'sX'         => '1',
                    'sY'         => '1',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => 'inherit',
                    'mX'         => '0px',
                    'mY'         => '0px',
                    'e'          => 'Power4.easeInOut',
                    'split'      => 'chars',
                    'splitDelay' => '10',
                ),

        ),
    'LettersFlyInFromRight'  =>
        array(
            'label'  => 'LettersFlyInFromRight',
            'config' =>
                array(
                    'x'          => '[105%]',
                    'y'          => 'inherit',
                    'z'          => '0',
                    'rX'         => '45deg',
                    'rY'         => '0deg',
                    'rZ'         => '90deg',
                    'sX'         => '1',
                    'sY'         => '1',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => 'inherit',
                    'mX'         => '0px',
                    'mY'         => '0px',
                    'e'          => 'Power4.easeInOut',
                    'split'      => 'chars',
                    'splitDelay' => '5',
                ),
        ),
    'LettersFlyInFromTop'    =>
        array(
            'label'  => 'LettersFlyInFromTop',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => '[-100%]',
                    'z'          => '0',
                    'rX'         => 'inherit',
                    'rY'         => 'inherit',
                    'rZ'         => '35deg',
                    'sX'         => '1',
                    'sY'         => '1',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => 'inherit',
                    'mX'         => '0px',
                    'mY'         => '0px',
                    'e'          => 'Power4.easeInOut',
                    'split'      => 'chars',
                    'splitDelay' => '5',
                ),
        ),
    'MaskedZoomOut'          =>
        array(
            'label'  => 'MaskedZoomOut',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => 'inherit',
                    'z'          => '0',
                    'rX'         => '0deg',
                    'rY'         => '0',
                    'rZ'         => '0',
                    'sX'         => '2',
                    'sY'         => '2',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => '0',
                    'mX'         => '0px',
                    'mY'         => '0px',
                    'e'          => 'Power2.easeOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'PopUpSmooth'            =>
        array(
            'label'  => 'PopUpSmooth',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => 'inherit',
                    'z'          => '0',
                    'rX'         => '0',
                    'rY'         => '0',
                    'rZ'         => '0',
                    'sX'         => '0.9',
                    'sY'         => '0.9',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => '0',
                    'mX'         => '0px',
                    'mY'         => 'top',
                    'e'          => 'Power3.easeInOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'RotateInFromBottom'     =>
        array(
            'label'  => 'RotateInFromBottom',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => 'bottom',
                    'z'          => 'inherit',
                    'rX'         => 'inherit',
                    'rY'         => 'inherit',
                    'rZ'         => '90deg',
                    'sX'         => '2',
                    'sY'         => '2',
                    'skX'        => 'inherit',
                    'skY'        => 'inherit',
                    'o'          => 'inherit',
                    'mX'         => '0',
                    'mY'         => '0',
                    'e'          => 'Power3.easeInOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'RotateInFormZero'       =>
        array(
            'label'  => 'RotateInFormZero',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => 'bottom',
                    'z'          => 'inherit',
                    'rX'         => '-20deg',
                    'rY'         => '-20deg',
                    'rZ'         => '0deg',
                    'sX'         => 'inherit',
                    'sY'         => 'inherit',
                    'skX'        => 'inherit',
                    'skY'        => 'inherit',
                    'o'          => 'inherit',
                    'mX'         => '0',
                    'mY'         => '0',
                    'e'          => 'Power3.easeOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SlideMaskFromBottom'    =>
        array(
            'label'  => 'SlideMaskFromBottom',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => '[100%]',
                    'z'          => '0',
                    'rX'         => '0deg',
                    'rY'         => '0',
                    'rZ'         => '0',
                    'sX'         => '1',
                    'sY'         => '1',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => '0',
                    'mX'         => '0px',
                    'mY'         => '[100%]',
                    'e'          => 'Power2.easeInOut',
                    'split'      => 'none',
                    'splitDelay' => '5',
                ),
        ),
    'SlideMaskFromLeft'      =>
        array(
            'label'  => 'SlideMaskFromLeft',
            'config' =>
                array(
                    'x'          => '[-100%]',
                    'y'          => 'inherit',
                    'z'          => '0',
                    'rX'         => '0deg',
                    'rY'         => '0',
                    'rZ'         => '0',
                    'sX'         => '1',
                    'sY'         => '1',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => 'inherit',
                    'mX'         => '0px',
                    'mY'         => '0px',
                    'e'          => 'Power3.easeInOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SlideMaskFromRight'     =>
        array(
            'label'  => 'SlideMaskFromRight',
            'config' =>
                array(
                    'x'          => '[100%]',
                    'y'          => 'inherit',
                    'z'          => '0',
                    'rX'         => '0deg',
                    'rY'         => '0',
                    'rZ'         => '0',
                    'sX'         => '1',
                    'sY'         => '1',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => 'inherit',
                    'mX'         => '0px',
                    'mY'         => '0px',
                    'e'          => 'Power3.easeInOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SlideMaskFromTop'       =>
        array(
            'label'  => 'SlideMaskFromTop',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => '[-100%]',
                    'z'          => '0',
                    'rX'         => '0deg',
                    'rY'         => '0',
                    'rZ'         => '0',
                    'sX'         => '1',
                    'sY'         => '1',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => 'inherit',
                    'mX'         => '0px',
                    'mY'         => '0px',
                    'e'          => 'Power3.easeInOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SmoothPopUp_One'        =>
        array(
            'label'  => 'SmoothPopUp_One',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => 'inherit',
                    'z'          => '0',
                    'rX'         => '0',
                    'rY'         => '0',
                    'rZ'         => '0',
                    'sX'         => '0.8',
                    'sY'         => '0.8',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => '0',
                    'mX'         => '0px',
                    'mY'         => 'top',
                    'e'          => 'Power4.easeOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SmoothPopUp_Two'        =>
        array(
            'label'  => 'SmoothPopUp_Two',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => 'inherit',
                    'z'          => '0',
                    'rX'         => '0',
                    'rY'         => '0',
                    'rZ'         => '0',
                    'sX'         => '0.9',
                    'sY'         => '0.9',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => '0',
                    'mX'         => '0px',
                    'mY'         => 'top',
                    'e'          => 'Power2.easeOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SmoothMaskFromRight'    =>
        array(
            'label'  => 'SmoothMaskFromRight',
            'config' =>
                array(
                    'x'          => '[-175%]',
                    'y'          => '0px',
                    'z'          => '0',
                    'rX'         => '0',
                    'rY'         => '0',
                    'rZ'         => '0',
                    'sX'         => '1',
                    'sY'         => '1',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => '1',
                    'mX'         => '[100%]',
                    'mY'         => '0',
                    'e'          => 'Power3.easeOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SmoothMaskFromLeft'     =>
        array(
            'label'  => 'SmoothMaskFromLeft',
            'config' =>
                array(
                    'x'          => '[175%]',
                    'y'          => '0px',
                    'z'          => '0',
                    'rX'         => '0',
                    'rY'         => '0',
                    'rZ'         => '0',
                    'sX'         => '1',
                    'sY'         => '1',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => '1',
                    'mX'         => '[-100%]',
                    'mY'         => '0',
                    'e'          => 'Power3.easeOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SmoothSlideFromBottom'  =>
        array(
            'label'  => 'SmoothSlideFromBottom',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => '[100%]',
                    'z'          => '0',
                    'rX'         => '0deg',
                    'rY'         => '0',
                    'rZ'         => '0',
                    'sX'         => '1',
                    'sY'         => '1',
                    'skX'        => '0',
                    'skY'        => '0',
                    'o'          => '0',
                    'mX'         => '0px',
                    'mY'         => '[100%]',
                    'e'          => 'Power4.easeInOut',
                    'split'      => 'none',
                    'splitDelay' => '5',
                ),
        ),
    'noanim'                 =>
        array(
            'label'  => 'No-Animation',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'tp-fade'                =>
        array(
            'label'  => 'Fade-In',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'sft'                    =>
        array(
            'label'  => 'Short-from-Top',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => '-50px',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'sfb'                    =>
        array(
            'label'  => 'Short-from-Bottom',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => '50px',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'sfl'                    =>
        array(
            'label'  => 'Short-From-Left',
            'config' =>
                array(
                    'x'   => '-50px',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'sfr'                    =>
        array(
            'label'  => 'Short-From-Right',
            'config' =>
                array(
                    'x'   => '50px',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'lfr'                    =>
        array(
            'label'  => 'Long-From-Right',
            'config' =>
                array(
                    'x'   => 'right',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'lfl'                    =>
        array(
            'label'  => 'Long-From-Left',
            'config' =>
                array(
                    'x'   => 'left',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'lft'                    =>
        array(
            'label'  => 'Long-From-Top',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => 'top',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'lfb'                    =>
        array(
            'label'  => 'Long-From-Bottom',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => 'bottom',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'skewfromleft'           =>
        array(
            'label'  => 'Skew-From-Long-Left',
            'config' =>
                array(
                    'x'   => 'left',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => '45px',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'skewfromright'          =>
        array(
            'label'  => 'Skew-From-Long-Right',
            'config' =>
                array(
                    'x'   => 'right',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => '-85px',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'skewfromleftshort'      =>
        array(
            'label'  => 'Skew-From-Short-Left',
            'config' =>
                array(
                    'x'   => '-200px',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => '85px',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'skewfromrightshort'     =>
        array(
            'label'  => 'Skew-From-Short-Right',
            'config' =>
                array(
                    'x'   => '200px',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => '-85px',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'randomrotate'           =>
        array(
            'label'  => 'Random-Rotate-and-Scale',
            'config' =>
                array(
                    'x'   => '{-250,250}',
                    'y'   => '{-150,150}',
                    'z'   => 'inherit',
                    'rX'  => '{-90,90}',
                    'rY'  => '{-90,90}',
                    'rZ'  => '{-360,360}',
                    'sX'  => '{0,1}',
                    'sY'  => '{0,1}',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
);

/**
 * Predefined out animations
 */
$settings['animations_out'] = array(
    'BounceOut'          =>
        array(
            'label'  => 'BounceOut',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => 'inherit',
                    'z'          => 'inherit',
                    'rX'         => 'inherit',
                    'rY'         => 'inherit',
                    'rZ'         => '0deg',
                    'sX'         => '0.7',
                    'sY'         => '0.7',
                    'skX'        => 'inherit',
                    'skY'        => 'inherit',
                    'o'          => '0',
                    'mX'         => '0',
                    'mY'         => '0',
                    'e'          => 'Back.easeIn',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'Fade-Out-Long'      =>
        array(
            'label'  => 'Fade-Out-Long',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => 'inherit',
                    'z'          => 'inherit',
                    'rX'         => 'inherit',
                    'rY'         => 'inherit',
                    'rZ'         => 'inherit',
                    'sX'         => 'inherit',
                    'sY'         => 'inherit',
                    'skX'        => 'inherit',
                    'skY'        => 'inherit',
                    'o'          => '0',
                    'mX'         => '0',
                    'mY'         => '0',
                    'e'          => 'Power2.easeIn',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SlideMaskToBottom'  =>
        array(
            'label'  => 'SlideMaskToBottom',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => '[100%]',
                    'z'          => 'inherit',
                    'rX'         => 'inherit',
                    'rY'         => 'inherit',
                    'rZ'         => 'inherit',
                    'sX'         => 'inherit',
                    'sY'         => 'inherit',
                    'skX'        => 'inherit',
                    'skY'        => 'inherit',
                    'o'          => 'inherit',
                    'mX'         => 'inherit',
                    'mY'         => 'inherit',
                    'e'          => 'nothing',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SlideMaskToLeft'    =>
        array(
            'label'  => 'SlideMaskToLeft',
            'config' =>
                array(
                    'x'          => '[-100%]',
                    'y'          => 'inherit',
                    'z'          => 'inherit',
                    'rX'         => 'inherit',
                    'rY'         => 'inherit',
                    'rZ'         => 'inherit',
                    'sX'         => 'inherit',
                    'sY'         => 'inherit',
                    'skX'        => 'inherit',
                    'skY'        => 'inherit',
                    'o'          => 'inherit',
                    'mX'         => 'inherit',
                    'mY'         => 'inherit',
                    'e'          => 'Power3.easeInOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SlideMaskToRight'   =>
        array(
            'label'  => 'SlideMaskToRight',
            'config' =>
                array(
                    'x'          => '[100%]',
                    'y'          => 'inherit',
                    'z'          => 'inherit',
                    'rX'         => 'inherit',
                    'rY'         => 'inherit',
                    'rZ'         => 'inherit',
                    'sX'         => 'inherit',
                    'sY'         => 'inherit',
                    'skX'        => 'inherit',
                    'skY'        => 'inherit',
                    'o'          => 'inherit',
                    'mX'         => 'inherit',
                    'mY'         => 'inherit',
                    'e'          => 'Power3.easeInOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SlideMaskToTop'     =>
        array(
            'label'  => 'SlideMaskToTop',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => '[-100%]',
                    'z'          => 'inherit',
                    'rX'         => 'inherit',
                    'rY'         => 'inherit',
                    'rZ'         => 'inherit',
                    'sX'         => 'inherit',
                    'sY'         => 'inherit',
                    'skX'        => 'inherit',
                    'skY'        => 'inherit',
                    'o'          => 'inherit',
                    'mX'         => 'inherit',
                    'mY'         => 'inherit',
                    'e'          => 'nothing',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SlurpOut'           =>
        array(
            'label'  => 'SlurpOut',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => '[100%]',
                    'z'          => 'inherit',
                    'rX'         => 'inherit',
                    'rY'         => 'inherit',
                    'rZ'         => '0deg',
                    'sX'         => '0.7',
                    'sY'         => '0.7',
                    'skX'        => 'inherit',
                    'skY'        => 'inherit',
                    'o'          => 'inherit',
                    'mX'         => '0',
                    'mY'         => '0',
                    'e'          => 'Power3.easeInOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'SmoothCropToBottom' =>
        array(
            'label'  => 'SmoothCropToBottom',
            'config' =>
                array(
                    'x'          => 'inherit',
                    'y'          => '[175%]',
                    'z'          => 'inherit',
                    'rX'         => 'inherit',
                    'rY'         => 'inherit',
                    'rZ'         => 'inherit',
                    'sX'         => 'inherit',
                    'sY'         => 'inherit',
                    'skX'        => 'inherit',
                    'skY'        => 'inherit',
                    'o'          => 'inherit',
                    'mX'         => 'inherit',
                    'mY'         => 'inherit',
                    'e'          => 'Power2.easeInOut',
                    'split'      => 'none',
                    'splitDelay' => '10',
                ),
        ),
    'noanimout'          =>
        array(
            'label'  => 'No-Out-Animation',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'fadeout'            =>
        array(
            'label'  => 'Fade-Out',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '0',
                ),
        ),
    'stt'                =>
        array(
            'label'  => 'Short-To-Top',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => '-50px',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'stb'                =>
        array(
            'label'  => 'Short-To-Bottom',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => '50px',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'stl'                =>
        array(
            'label'  => 'Short-To-Left',
            'config' =>
                array(
                    'x'   => '-50px',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'str'                =>
        array(
            'label'  => 'Short-To-Right',
            'config' =>
                array(
                    'x'   => '50px',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'ltr'                =>
        array(
            'label'  => 'Long-To-Right',
            'config' =>
                array(
                    'x'   => 'right',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'ltl'                =>
        array(
            'label'  => 'Long-To-Left',
            'config' =>
                array(
                    'x'   => 'left',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'ltt'                =>
        array(
            'label'  => 'Long-To-Top',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => 'top',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'ltb'                =>
        array(
            'label'  => 'Long-To-Bottom',
            'config' =>
                array(
                    'x'   => 'inherit',
                    'y'   => 'bottom',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'skewtoleft'         =>
        array(
            'label'  => 'Skew-To-Long-Left',
            'config' =>
                array(
                    'x'   => 'left',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => '45px',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'skewtoright'        =>
        array(
            'label'  => 'Skew-To-Long-Right',
            'config' =>
                array(
                    'x'   => 'right',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => '-85px',
                    'skY' => 'inherit',
                    'o'   => 'inherit',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'skewtorightshort'   =>
        array(
            'label'  => 'Skew-To-Short-Right',
            'config' =>
                array(
                    'x'   => '200px',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => '-85px',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'skewtoleftshort'    =>
        array(
            'label'  => 'Skew-To-Short-Left',
            'config' =>
                array(
                    'x'   => '-200px',
                    'y'   => 'inherit',
                    'z'   => 'inherit',
                    'rX'  => 'inherit',
                    'rY'  => 'inherit',
                    'rZ'  => 'inherit',
                    'sX'  => 'inherit',
                    'sY'  => 'inherit',
                    'skX' => '85px',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
    'randomrotateout'    =>
        array(
            'label'  => 'Random-Rotate-Out',
            'config' =>
                array(
                    'x'   => '{-250,250}',
                    'y'   => '{-150,150}',
                    'z'   => 'inherit',
                    'rX'  => '{-90,90}',
                    'rY'  => '{-90,90}',
                    'rZ'  => '{-360,360}',
                    'sX'  => '{0,1}',
                    'sY'  => '{0,1}',
                    'skX' => 'inherit',
                    'skY' => 'inherit',
                    'o'   => '0',
                    'mX'  => '0',
                    'mY'  => '0',
                    's'   => '500',
                ),
        ),
);

/**
 * DO NOT REMOVE!
 */
return $settings;
