<?php
/**
 * TL_ROOT/system/modules/autoregistration/languages/fr/modules.php 
 * 
 * Contao extension: autoregistration 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Michel LAURENT (equipc), http://www.equipc.net 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['autoregistration']['0'] = "Activation/Connexion automatique des nouveaux membres";
 
?>
