<?php
/**
 * TL_ROOT/system/modules/autoregistration/languages/fr/tl_page.php 
 * 
 * Contao extension: autoregistration 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Michel LAURENT (equipc), http://www.equipc.net 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['auto_activate_registration']['0'] = "Activation automatique";
$GLOBALS['TL_LANG']['tl_page']['auto_activate_registration']['1'] = "Les nouveaux membres seront automatiquement activés (sans confirmation par email)";
$GLOBALS['TL_LANG']['tl_page']['auto_login_registration']['0'] = "Connexion automatique";
$GLOBALS['TL_LANG']['tl_page']['auto_login_registration']['1'] = "Les nouveaux membres seront automatiquement connectés (fonctionne uniquement si l'activation automatique est activée).";
$GLOBALS['TL_LANG']['tl_page']['auto_login_activation']['0'] = "Connexion automatique lors de l'activation";
$GLOBALS['TL_LANG']['tl_page']['auto_login_activation']['1'] = "Si coché, les nouveaux membres seront automatiquement connecté lorsqu'ils confirmeront leur activation.";
$GLOBALS['TL_LANG']['tl_page']['registration_legend'] = "Enregistrement des membres";
 
?>
